---
apiVersion: v1
kind: Service
metadata:
  name: registration-app-nlb-service
  labels:
    app: registration-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer 
  selector:
   app: registration-app
  ports:
    - port: 80
      targetPort: 8080
   