apiVersion: v1
kind: Service
metadata:
  name: registration-app-service
spec:
  type: NodePort 
  selector:
   app: registration-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31280